### ISSUE TITLE
some issues 

### ISSUE THREAD

**Issue by havefun77612** [unstabl3/breakfold#1]
too many problem here 

log : 

Traceback (most recent call last):
  File "breakfold.py", line 113, in <module>
    visit()
  File "breakfold.py", line 95, in visit
    session.get(address, headers=header)	#visiting the URL given by the user
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 370, in send
    conn = self.get_connection(request.url, proxies)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 273, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 169, in proxy_manager_for
    **proxy_kwargs
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 43, in SOCKSProxyManager
    raise InvalidSchema("Missing dependencies for SOCKS support.")
requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.

**Comment by unstabl3** [comment]
Hi @havefun77612 
Did you install the stem library using pip? (pip3 if python3)
Did you follow all the steps I mentioned in the installation?
If yes can you give me some more details? (os, python version)

**Comment by havefun77612** [comment]
I've tried each step you've mentioned
I've try using python2 and the program said it need python3 to work so I follow it
And yes I used pip install stem and also used pip3 install stem

OS Ubuntu 17
Device : VMware

**Comment by rori4** [comment]
I also have the same issue on this

**Comment by unstabl3** [comment]
will look into this!

**Comment by webzf** [comment]
That requests is using socks as a proxy and that socks is not installed.

Just run pip install pysocks

**Comment by unstabl3** [comment]
Hi, @rori4 @havefun77612 sorry for the delay!
As @webzf mentioned pysocks will solve the problem!
I will add pysocks as a dependency to the readme.

Thanks,

**Comment by ChoiWooYoung** [comment]
I solve that problem using
```
python3 -m pip install -U requests[socks]
```
in terminal.

**Comment by unstabl3** [comment]
Closing this now!
Be safe everyone!!

**Comment by Learner-Manu** [comment]
After updating CookieAuthentication 1, restarted  tor services and it worked for me.
