### ISSUE TITLE
Seems Code is throwing error

### ISSUE THREAD

**Issue by Learner-Manu** [unstabl3/breakfold#3]
Just followed the instruction provided and getting the below error, Could you please guide on the fix

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/stem/socket.py", line 535, in _make_socket
    control_socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "breakfold.py", line 113, in <module>
    visit()
  File "breakfold.py", line 105, in visit
    renew_connection()
  File "breakfold.py", line 51, in renew_connection
    with Controller.from_port(address="127.0.0.1", port = 9051) as controller:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/stem/control.py", line 1033, in from_port
    control_port = stem.socket.ControlPort(address, port)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/stem/socket.py", line 503, in __init__
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/stem/socket.py", line 172, in connect
    self._socket = self._make_socket()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/stem/socket.py", line 538, in _make_socket
    raise stem.SocketError(exc)
stem.SocketError: [Errno 61] Connection refused

**Comment by unstabl3** [comment]
hi @Learner-Manu 

From the above log, I can only guess that your tor service is not running.
Also, it is working fine for me!

If you are still having a problem, please give some more details!

**Comment by aryamansharda** [comment]
I'm having the exact same issue :/
```
  File "/usr/local/lib/python3.6/dist-packages/stem/socket.py", line 535, in _make_socket
    control_socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by unstabl3** [comment]
Hi @aryamansharda 
With the amount of information, you have provided I can only tell that this is because your tor service is not working!
As I said earlier also this is working fine for me!
Take care,
shubham

**Comment by unstabl3** [comment]
Closing this for Now! You can reopen if you are still facing problem! :)
Take care,
shubham
