### ISSUE TITLE
im getting an error donno why 

### ISSUE THREAD

**Issue by beniwallokendra** [unstabl3/breakfold#9]
Enter blog address:  https://lokisenpai.blogspot.com/2022/09/sasaki-and-miyano-my-first-bl-anime.html
 How many views you want: 4
Traceback (most recent call last):
  File "/home/loki/.local/lib/python3.10/site-packages/socks.py", line 787, in connect
    super(socksocket, self).connect(proxy_addr)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/contrib/socks.py", line 96, in _new_conn
    conn = socks.create_connection(
  File "/home/loki/.local/lib/python3.10/site-packages/socks.py", line 209, in create_connection
    raise err
  File "/home/loki/.local/lib/python3.10/site-packages/socks.py", line 199, in create_connection
    sock.connect((remote_host, remote_port))
  File "/home/loki/.local/lib/python3.10/site-packages/socks.py", line 47, in wrapper
    return function(*args, **kwargs)
  File "/home/loki/.local/lib/python3.10/site-packages/socks.py", line 800, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy localhost:9050: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/contrib/socks.py", line 127, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f9e8732eda0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='lokisenpai.blogspot.com', port=443): Max retries exceeded with url: /2022/09/sasaki-and-miyano-my-first-bl-anime.html (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f9e8732eda0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/loki/Documents/TOOLS/breakfold/breakfold.py", line 113, in <module>
    visit()
  File "/home/loki/Documents/TOOLS/breakfold/breakfold.py", line 95, in visit
    session.get(address, headers=header)	#visiting the URL given by the user
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: SOCKSHTTPSConnectionPool(host='lokisenpai.blogspot.com', port=443): Max retries exceeded with url: /2022/09/sasaki-and-miyano-my-first-bl-anime.html (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f9e8732eda0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by blloyd78** [comment]
I'm having the exact same problem. Is the ISP blocking TOR traffic?

**Comment by papaganesha** [comment]
me too, after the password error now this
